"""Merge solver shards (tool/out/*.jsonl) into lib/game/hints.g.dart."""
import glob
import json
import os

ROOT = os.path.join(os.path.dirname(__file__), '..')
# newest solved result per key wins (lines without a timestamp count as oldest)
results = {}
for path in sorted(glob.glob(os.path.join(ROOT, 'tool', 'out', '*.jsonl'))):
    for line in open(path, encoding='utf-8'):
        if line.strip():
            m = json.loads(line)
            old = results.get(m['key'])
            if old is None or (m['hint'] is not None and (old['hint'] is None or m.get('t', 0) >= old.get('t', 0))):
                results[m['key']] = m


def order(k):
    return ('cbx'.index(k[0]), int(k[1:]))


keys = sorted(results, key=order)
unsolved = [k for k in keys if results[k]['hint'] is None]
variants = ', '.join(f"'{k}': {results[k]['v']}" for k in keys if results[k]['hint'] is not None and results[k]['v'])
lines = [
    '// Generated by tool/solve_levels.dart + tool/merge_hints.py. Do not edit by hand.',
    "import 'dart:ui';",
    '',
    f'const Map<String, int> kVariants = {{{variants}}};',
    '',
    'const Map<String, List<List<Offset>>> kSolvedHints = {',
]
for k in keys:
    h = results[k]['hint']
    if h is None:
        continue
    strokes = ', '.join('[' + ', '.join(f'Offset({x:.1f}, {y:.1f})' for x, y in s) + ']' for s in h)
    lines.append(f"  '{k}': [{strokes}],")
lines.append('};')
open(os.path.join(ROOT, 'lib', 'game', 'hints.g.dart'), 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
print(f'{len(keys) - len(unsolved)} solved, unsolved: {unsolved}')
